// #1076 Phase 5a: P.3 audit found all Legolas test PixelPoint sites are
// overlay-frame, so this Rendering test file was migrated alongside the 5a
// scope (its PinScene/drawer dependencies now take OverlayPixel).
using FluentAssertions;
using Legolas.Domain;
using Legolas.Rendering;
using Mithril.MapCalibration;
using Mithril.Overlay;
using Mithril.Overlay.Internal;
using Color = System.Windows.Media.Color;
using Color4 = Vortice.Mathematics.Color4;

namespace Legolas.Tests.Rendering;

/// <summary>
/// Byte-parity snapshot tests for the #835-step-2 marker drawers. Each test
/// builds a deterministic <see cref="PinScene"/> fixture, renders it via the
/// existing <see cref="PinSceneRenderer"/> to a baseline PNG, then builds the
/// equivalent marker list + style set, renders via the new
/// <see cref="MarkerSceneRenderer"/> + Legolas drawers to a second PNG, and
/// asserts the two PNG byte streams are identical against the **checked-in
/// baseline on disk** (never against a freshly-regenerated baseline at
/// run-time — see B1 fix below).
///
/// <para><b>Dual role for these tests.</b> This PR (step 2) uses them as a
/// parity guard &#8212; PinSceneRenderer is the source of truth and the new
/// drawers must reproduce it. Step 6 will delete PinSceneRenderer; the same
/// tests then become regression guards against the checked-in baseline PNGs,
/// catching any later drift in the new drawer implementation.</para>
///
/// <para><b>B1 (review-iteration-2): no auto-regen-on-missing.</b> If a
/// baseline PNG is missing from disk the test fails hard with a
/// <see cref="FileNotFoundException"/> directing the developer to set
/// <c>MITHRIL_REGEN_SNAPSHOTS=1</c> and re-run. With the env var set, the
/// test writes the regenerated baseline and throws so the run still fails —
/// the developer is forced to re-run *without* the env var to verify both
/// PinSceneRenderer and the new drawer match the freshly-regenerated bytes.
/// The old "silently write on first run + ReferenceEquals shortcut" path
/// was a tautological-pass trapdoor: only `new drawer == current
/// PinSceneRenderer` was asserted; the post-step-6 regression-guard
/// contract was defeated. Drift-check is now unconditional.</para>
///
/// <para><b>Headless CI gating.</b>
/// <see cref="HeadlessD2DRenderTarget.TryCreate"/> attempts hardware D3D11
/// first, then WARP. If both fail the test is *Skipped* (not failed) via
/// <see cref="Skip.If(bool, string)"/> from <c>Xunit.SkippableFact</c>, with
/// the captured driver-construction exception's message in the Skip
/// diagnostic. Per scaffold PR #850's note that headless CI may reject
/// D3D11 device creation entirely. Truly headless CI without WARP shows up
/// as "Skipped" in the runner, never as a silent green pass.</para>
///
/// <para><b>Calibration drawer absent.</b> Per the issue body for #835,
/// today's calibration markers are drawn by a WPF <c>ItemsControl</c>
/// (per the <c>#495</c> comment in <see cref="PinSceneRenderer"/>), not by
/// the D2D renderer. There is no <c>PinSceneRenderer</c> branch to
/// byte-parity-compare against, so the calibration drawer ships in step 5
/// when the calibration markers switch over to D2D.</para>
/// </summary>
public sealed class LegolasMarkerDrawerSnapshotTests
{
    private const int CanvasWidth = 240;
    private const int CanvasHeight = 240;

    /// <summary>Env-var flag that opts the developer into baseline regeneration.
    /// Required after B1: missing baselines fail hard without it, so a stale
    /// or deleted PNG can't silently pass as a fresh-write.</summary>
    private const string RegenEnvVar = "MITHRIL_REGEN_SNAPSHOTS";

    /// <summary>
    /// Skip-message preamble for the headless-D3D11 path. The captured
    /// driver-construction exception (from <c>TryCreate</c>'s out-param) is
    /// concatenated by the caller so investigators see the *actual* cause,
    /// not a generic "no driver" claim.
    /// </summary>
    private const string SkipNoD3DPrefix =
        "No usable D3D11 driver (neither Hardware nor WARP). Expected on truly headless CI "
        + "with no graphics drivers installed; tests run locally + on CI images that ship the "
        + "WARP software adapter. Inner driver error: ";

    private static readonly Color CyanFill = Color.FromArgb(0xFF, 0x00, 0xFF, 0xFF);
    private static readonly Color WhiteStroke = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);
    private static readonly Color GoldStroke = Color.FromArgb(0xFF, 0xFF, 0xD2, 0x3F);
    private static readonly Color Green = Color.FromArgb(0xFF, 0x4C, 0xAF, 0x50);
    private static readonly Color RouteColor = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);

    private static PinLayerStyle SurveyOuterStyle() => new(
        Shape: PinShape.Circle,
        FillColor: Color.FromArgb(1, 0, 0, 0), // near-transparent fill, matches default
        StrokeColor: CyanFill,
        StrokeStyle: PinStrokeStyle.Dashed,
        StrokeThickness: 2.0,
        Size: 0);

    private static PinLayerStyle SurveyCenterStyle() => new(
        Shape: PinShape.Circle,
        FillColor: CyanFill,
        StrokeColor: Color.FromArgb(0, 0, 0, 0),
        StrokeStyle: PinStrokeStyle.None,
        StrokeThickness: 0,
        Size: 5.0);

    private static PinLayerStyle PlayerOuterStyle() => new(
        Shape: PinShape.Circle,
        FillColor: Color.FromArgb(0, 0, 0, 0),
        StrokeColor: WhiteStroke,
        StrokeStyle: PinStrokeStyle.Solid,
        StrokeThickness: 2.0,
        Size: 18.0);

    private static PinLayerStyle PlayerCenterStyle() => new(
        Shape: PinShape.Square,
        FillColor: Green,
        StrokeColor: Color.FromArgb(0, 0, 0, 0),
        StrokeStyle: PinStrokeStyle.None,
        StrokeThickness: 0,
        Size: 2.0);

    [SkippableFact]
    public void Survey_pin_default_style_byte_matches_PinSceneRenderer()
    {
        RunSnapshotComparison(
            fixtureName: "survey_default",
            scene: BuildSceneWithSinglePin(activeIndex: null, treatment: null),
            markers: new (OverlayPixel, IMarkerStyle)[]
            {
                (new OverlayPixel(120, 120), new LegolasSurveyMarkerStyle(
                    Outer: SurveyOuterStyle(),
                    Center: SurveyCenterStyle(),
                    OuterDiameter: 24.0,
                    ActiveTreatment: null)),
            });
    }

    [SkippableTheory]
    [InlineData(ActivePinTreatment.Halo)]
    [InlineData(ActivePinTreatment.Glow)]
    [InlineData(ActivePinTreatment.ScaleUp)]
    [InlineData(ActivePinTreatment.FillSwap)]
    public void Survey_active_pin_byte_matches_PinSceneRenderer(ActivePinTreatment treatment)
    {
        var spec = new ActivePinTreatmentSpec(
            Treatment: treatment,
            Color: WhiteStroke,
            HaloPaddingPx: 3.0,
            StrokeThickness: 2.0,
            GlowBlurRadius: 12.0);
        RunSnapshotComparison(
            fixtureName: "survey_active_" + treatment.ToString().ToLowerInvariant(),
            scene: BuildSceneWithSinglePin(activeIndex: 0, treatment: spec),
            markers: new (OverlayPixel, IMarkerStyle)[]
            {
                (new OverlayPixel(120, 120), new LegolasSurveyMarkerStyle(
                    Outer: SurveyOuterStyle(),
                    Center: SurveyCenterStyle(),
                    OuterDiameter: 24.0,
                    ActiveTreatment: spec)),
            });
    }

    /// <summary>
    /// B3 (review-iteration-2): the Motherlode fixture intentionally uses a
    /// distinct pixel anchor (<c>(140, 110)</c>) AND a distinct outer
    /// diameter (<c>30.0</c>) from the Survey-default fixture (<c>(120, 120)</c>
    /// + <c>24.0</c>). The two baselines previously had identical SHA-256
    /// hashes — both rendered an identical pin at the same position with the
    /// same styles, so the Motherlode-pin parity test provided zero
    /// coverage over Survey-default. A bug routing
    /// <see cref="LegolasMotherlodeMarkerDrawer"/> to the wrong shared
    /// helper would still pass. Differentiating the input forces a
    /// distinguishable byte stream.
    /// </summary>
    [SkippableFact]
    public void Motherlode_pin_byte_matches_PinSceneRenderer()
    {
        RunSnapshotComparison(
            fixtureName: "motherlode_pin",
            scene: BuildSceneWithMotherlodePin(includeGuidance: false),
            markers: new (OverlayPixel, IMarkerStyle)[]
            {
                (new OverlayPixel(140, 110), new LegolasMotherlodeMarkerStyle(
                    Outer: SurveyOuterStyle(),
                    Center: SurveyCenterStyle(),
                    OuterDiameter: 30.0)),
            });
    }

    [SkippableFact]
    public void Motherlode_guidance_circle_byte_matches_PinSceneRenderer()
    {
        RunSnapshotComparison(
            fixtureName: "motherlode_guidance",
            scene: BuildSceneWithMotherlodeGuidance(),
            markers: new (OverlayPixel, IMarkerStyle)[]
            {
                (new OverlayPixel(120, 120),
                 new LegolasMotherlodeGuidanceMarkerStyle(RadiusPixels: 60.0, StrokeColor: GoldStroke)),
            });
    }

    [SkippableFact]
    public void Player_anchor_byte_matches_PinSceneRenderer()
    {
        RunSnapshotComparison(
            fixtureName: "player_anchor",
            scene: BuildSceneWithPlayerAnchor(),
            markers: new (OverlayPixel, IMarkerStyle)[]
            {
                (new OverlayPixel(120, 120), new LegolasPlayerMarkerStyle(
                    Outer: PlayerOuterStyle(),
                    Center: PlayerCenterStyle())),
            });
    }

    /// <summary>
    /// B4 (review-iteration-2): every other fixture in this class is single-
    /// marker — none exercise <see cref="MarkerSceneRenderer.Render"/>'s
    /// for-loop. A bug that drops every-other marker, breaks iteration order,
    /// or silently drops markers with an unregistered style (per the v1
    /// design: <c>_missingDrawerLogged.TryAdd</c> + counter increment, no
    /// exception) would never surface. This fixture renders THREE distinct
    /// Survey pins — one Halo-active and two plain — at distinct pixels and
    /// asserts byte-parity against a <c>PinSceneRenderer</c> baseline that
    /// renders the equivalent <see cref="PinScene"/> (SurveyPins list of
    /// three points + ActivePinIndex = 0). Iteration order matters: the
    /// active pin is rendered LAST by <c>PinSceneRenderer.DrawSurveyPins</c>
    /// (so the halo can't be occluded by neighbouring pins), so the marker
    /// list also places the active pin last.
    /// </summary>
    [SkippableFact]
    public void Multi_marker_survey_dispatch_byte_matches_PinSceneRenderer()
    {
        var spec = new ActivePinTreatmentSpec(
            Treatment: ActivePinTreatment.Halo,
            Color: WhiteStroke,
            HaloPaddingPx: 3.0,
            StrokeThickness: 2.0,
            GlowBlurRadius: 12.0);

        // Three pins at distinct pixels. Pin index 2 (last) is the active
        // one — matches PinSceneRenderer.DrawSurveyPins's "non-active first,
        // then active on top" ordering.
        var pinPixels = new[]
        {
            new OverlayPixel(80, 100),
            new OverlayPixel(160, 100),
            new OverlayPixel(120, 180),
        };
        var scene = BuildMultiPinSurveyScene(pinPixels, activeIndex: 2, treatment: spec);

        // Marker list mirrors that order. Two plain markers, then the
        // active one with the treatment. The Mithril.Overlay-facing marker
        // tuple is OverlayPixel (#1076) but PinScene's OverlayPixel pixels are
        // still the byte-parity reference — convert at the boundary so both
        // sides receive the same coordinates.
        var markers = new List<(OverlayPixel, IMarkerStyle)>
        {
            (new OverlayPixel(pinPixels[0].X, pinPixels[0].Y), new LegolasSurveyMarkerStyle(
                SurveyOuterStyle(), SurveyCenterStyle(), 24.0, ActiveTreatment: null)),
            (new OverlayPixel(pinPixels[1].X, pinPixels[1].Y), new LegolasSurveyMarkerStyle(
                SurveyOuterStyle(), SurveyCenterStyle(), 24.0, ActiveTreatment: null)),
            (new OverlayPixel(pinPixels[2].X, pinPixels[2].Y), new LegolasSurveyMarkerStyle(
                SurveyOuterStyle(), SurveyCenterStyle(), 24.0, ActiveTreatment: spec)),
        };

        RunSnapshotComparison(fixtureName: "multi_marker_survey", scene: scene, markers: markers);
    }

    // -----------------------------------------------------------------
    // Scene builders
    // -----------------------------------------------------------------

    private static PinScene BuildSceneWithSinglePin(int? activeIndex, ActivePinTreatmentSpec? treatment) =>
        new(
            RoutePoints: Array.Empty<OverlayPixel>(),
            ActiveSegmentPoints: Array.Empty<OverlayPixel>(),
            Wedges: Array.Empty<WedgeArc>(),
            SurveyPins: new[] { new OverlayPixel(120, 120) },
            MotherlodePins: Array.Empty<OverlayPixel>(),
            MotherlodeGuidance: null,
            ActivePinIndex: activeIndex,
            ActiveTreatment: treatment,
            SurveyOuter: SurveyOuterStyle(),
            SurveyCenter: SurveyCenterStyle(),
            SurveyOuterDiameter: 24.0,
            PlayerPosition: null,
            PlayerOuter: PlayerOuterStyle(),
            PlayerCenter: PlayerCenterStyle(),
            RouteLineColor: RouteColor,
            WedgeFillColor: Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF),
            WedgeStrokeColor: WhiteStroke,
            ActiveSegmentDashOffset: 0);

    private static PinScene BuildMultiPinSurveyScene(
        IReadOnlyList<OverlayPixel> pinPixels,
        int activeIndex,
        ActivePinTreatmentSpec treatment) =>
        new(
            RoutePoints: Array.Empty<OverlayPixel>(),
            ActiveSegmentPoints: Array.Empty<OverlayPixel>(),
            Wedges: Array.Empty<WedgeArc>(),
            SurveyPins: pinPixels,
            MotherlodePins: Array.Empty<OverlayPixel>(),
            MotherlodeGuidance: null,
            ActivePinIndex: activeIndex,
            ActiveTreatment: treatment,
            SurveyOuter: SurveyOuterStyle(),
            SurveyCenter: SurveyCenterStyle(),
            SurveyOuterDiameter: 24.0,
            PlayerPosition: null,
            PlayerOuter: PlayerOuterStyle(),
            PlayerCenter: PlayerCenterStyle(),
            RouteLineColor: RouteColor,
            WedgeFillColor: Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF),
            WedgeStrokeColor: WhiteStroke,
            ActiveSegmentDashOffset: 0);

    // B3: the Motherlode fixture deliberately diverges from Survey-default's
    // (120, 120) pixel + 24px diameter — see attribute docs on
    // Motherlode_pin_byte_matches_PinSceneRenderer for why.
    private static PinScene BuildSceneWithMotherlodePin(bool includeGuidance) =>
        new(
            RoutePoints: Array.Empty<OverlayPixel>(),
            ActiveSegmentPoints: Array.Empty<OverlayPixel>(),
            Wedges: Array.Empty<WedgeArc>(),
            SurveyPins: Array.Empty<OverlayPixel>(),
            MotherlodePins: new[] { new OverlayPixel(140, 110) },
            MotherlodeGuidance: includeGuidance
                ? new MotherlodeGuidanceCircle(new OverlayPixel(140, 110), 60.0, GoldStroke)
                : null,
            ActivePinIndex: null,
            ActiveTreatment: null,
            SurveyOuter: SurveyOuterStyle(),
            SurveyCenter: SurveyCenterStyle(),
            SurveyOuterDiameter: 30.0,
            PlayerPosition: null,
            PlayerOuter: PlayerOuterStyle(),
            PlayerCenter: PlayerCenterStyle(),
            RouteLineColor: RouteColor,
            WedgeFillColor: Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF),
            WedgeStrokeColor: WhiteStroke,
            ActiveSegmentDashOffset: 0);

    private static PinScene BuildSceneWithMotherlodeGuidance() =>
        new(
            RoutePoints: Array.Empty<OverlayPixel>(),
            ActiveSegmentPoints: Array.Empty<OverlayPixel>(),
            Wedges: Array.Empty<WedgeArc>(),
            SurveyPins: Array.Empty<OverlayPixel>(),
            MotherlodePins: Array.Empty<OverlayPixel>(),
            MotherlodeGuidance: new MotherlodeGuidanceCircle(new OverlayPixel(120, 120), 60.0, GoldStroke),
            ActivePinIndex: null,
            ActiveTreatment: null,
            SurveyOuter: SurveyOuterStyle(),
            SurveyCenter: SurveyCenterStyle(),
            SurveyOuterDiameter: 24.0,
            PlayerPosition: null,
            PlayerOuter: PlayerOuterStyle(),
            PlayerCenter: PlayerCenterStyle(),
            RouteLineColor: RouteColor,
            WedgeFillColor: Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF),
            WedgeStrokeColor: WhiteStroke,
            ActiveSegmentDashOffset: 0);

    private static PinScene BuildSceneWithPlayerAnchor() =>
        new(
            RoutePoints: Array.Empty<OverlayPixel>(),
            ActiveSegmentPoints: Array.Empty<OverlayPixel>(),
            Wedges: Array.Empty<WedgeArc>(),
            SurveyPins: Array.Empty<OverlayPixel>(),
            MotherlodePins: Array.Empty<OverlayPixel>(),
            MotherlodeGuidance: null,
            ActivePinIndex: null,
            ActiveTreatment: null,
            SurveyOuter: SurveyOuterStyle(),
            SurveyCenter: SurveyCenterStyle(),
            SurveyOuterDiameter: 24.0,
            PlayerPosition: new OverlayPixel(120, 120),
            PlayerOuter: PlayerOuterStyle(),
            PlayerCenter: PlayerCenterStyle(),
            RouteLineColor: RouteColor,
            WedgeFillColor: Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF),
            WedgeStrokeColor: WhiteStroke,
            ActiveSegmentDashOffset: 0);

    // -----------------------------------------------------------------
    // Render comparison core
    // -----------------------------------------------------------------

    private static void RunSnapshotComparison(
        string fixtureName,
        PinScene scene,
        IReadOnlyList<(OverlayPixel, IMarkerStyle)> markers)
    {
        // R-C1 (review-iteration-2): real Skip, not a failed assertion. If
        // no D3D11 driver is available the runner reports "Skipped: <reason>"
        // and the captured driver-construction exception goes into the
        // diagnostic so investigators see the actual cause (B2). Pre-R-C1
        // this was a Should().NotBeNull which produced a red failed test.
        using var baselineRt = HeadlessD2DRenderTarget.TryCreate(
            CanvasWidth, CanvasHeight, out var baselineDriverError);
        Skip.If(baselineRt is null, SkipNoD3DPrefix + (baselineDriverError?.Message ?? "(unknown)"));

        var freshBaselinePng = RenderBaselinePng(baselineRt!, scene);

        // B1 (review-iteration-2): the on-disk baseline is the single source
        // of truth. If it's missing, hard-fail (or write-and-fail under the
        // env-var). Drift check is unconditional below — no ReferenceEquals
        // shortcut that lets a freshly-written baseline pass tautologically.
        var baselinePath = ResolveBaselinePath(fixtureName);
        var baselinePng = LoadBaselineOrFail(baselinePath, freshBaselinePng);

        // Drift gate: PinSceneRenderer must still produce the same bytes as
        // the checked-in baseline today. Unconditional — runs even when the
        // env-var regen just wrote the fresh bytes, because the re-run
        // *without* the env-var is the developer's verification step.
        freshBaselinePng.Should().Equal(baselinePng,
            "PinSceneRenderer's output drifted from the checked-in baseline at "
            + baselinePath + " — if this is intentional (e.g. a bug fix in the "
            + "legacy renderer during the migration window), regenerate the "
            + "baseline by setting " + RegenEnvVar + "=1 and re-running this test, "
            + "then re-run again without the env var to verify.");

        using var newRt = HeadlessD2DRenderTarget.TryCreate(
            CanvasWidth, CanvasHeight, out var newDriverError);
        Skip.If(newRt is null, SkipNoD3DPrefix + (newDriverError?.Message ?? "(unknown)"));

        var newPng = RenderNewPipelinePng(newRt!, markers);

        newPng.Should().Equal(baselinePng,
            "the new marker drawer must produce byte-identical D2D output to "
            + "the legacy PinSceneRenderer; this is the parity guarantee that lets "
            + "step 6 retire PinSceneRenderer without visual regression. "
            + "Snapshot test also serves post-step-6 as regression guard against the "
            + "checked-in baseline at " + baselinePath
            + " (see class-level docs).");
    }

    /// <summary>
    /// Resolve the absolute path to the checked-in baseline PNG for the
    /// given fixture. We read from the source tree (relative to
    /// <see cref="AppContext.BaseDirectory"/>) so a regeneration under the
    /// env-var updates the checked-in copy directly.
    /// <c>AppContext.BaseDirectory</c> is <c>bin/Debug/net10.0-windows/</c>,
    /// three "..": <c>tests/Legolas.Tests/Rendering/Snapshots/Baselines/</c>.
    /// </summary>
    private static string ResolveBaselinePath(string fixtureName)
    {
        var dllDir = AppContext.BaseDirectory;
        var baselineDir = System.IO.Path.GetFullPath(
            System.IO.Path.Combine(dllDir, "..", "..", "..", "Rendering", "Snapshots", "Baselines"));
        System.IO.Directory.CreateDirectory(baselineDir);
        return System.IO.Path.Combine(baselineDir, fixtureName + ".png");
    }

    /// <summary>
    /// B1 (review-iteration-2): load the baseline PNG from disk. If missing,
    /// fail loud. If missing AND the <see cref="RegenEnvVar"/> env-var is
    /// set to "1", write the supplied fresh bytes to disk *and* throw — the
    /// developer must re-run without the env-var to actually verify parity
    /// against the just-written baseline. Auto-write-then-pass on first run
    /// (the pre-iteration-2 behaviour) was a tautological-pass trapdoor:
    /// only `new drawer == current PinSceneRenderer` was asserted in that
    /// path, defeating the post-step-6 regression-guard contract.
    /// </summary>
    private static byte[] LoadBaselineOrFail(string path, byte[] freshBaselinePng)
    {
        if (System.IO.File.Exists(path))
        {
            return System.IO.File.ReadAllBytes(path);
        }

        if (Environment.GetEnvironmentVariable(RegenEnvVar) == "1")
        {
            System.IO.File.WriteAllBytes(path, freshBaselinePng);
            throw new Xunit.Sdk.XunitException(
                "Regenerated missing baseline at " + path
                + ". Re-run WITHOUT " + RegenEnvVar
                + "=1 to verify that both PinSceneRenderer and the new drawer "
                + "produce these bytes; the regen run intentionally fails so "
                + "the verify step is not skipped.");
        }

        throw new System.IO.FileNotFoundException(
            "Snapshot baseline missing: " + path
            + ". Set " + RegenEnvVar + "=1 to regenerate, then re-run without it. "
            + "Auto-write-on-missing was removed in #835 review-iteration-2 to "
            + "close the tautological-pass trapdoor (the first run would write "
            + "the current PinSceneRenderer output and assert it against itself).",
            path);
    }

    private static byte[] RenderBaselinePng(HeadlessD2DRenderTarget rt, PinScene scene)
    {
        using var brushes = new D2DBrushCache();
        brushes.Bind(rt.RenderTarget);
        rt.RenderTarget.BeginDraw();
        rt.RenderTarget.Clear(new Color4(0, 0, 0, 0));
        PinSceneRenderer.Render(scene, rt.RenderTarget, rt.Factory, brushes);
        rt.RenderTarget.EndDraw();
        return rt.EncodePng();
    }

    private static byte[] RenderNewPipelinePng(
        HeadlessD2DRenderTarget rt,
        IReadOnlyList<(OverlayPixel, IMarkerStyle)> markers)
    {
        var sceneRenderer = new MarkerSceneRenderer();
        LegolasOverlayDrawerRegistrations.RegisterAll(sceneRenderer);

        using var brushes = new D2DBrushCache();
        brushes.Bind(rt.RenderTarget);
        rt.RenderTarget.BeginDraw();
        rt.RenderTarget.Clear(new Color4(0, 0, 0, 0));
        sceneRenderer.Render(markers, rt.RenderTarget, rt.Factory, brushes);
        rt.RenderTarget.EndDraw();
        return rt.EncodePng();
    }
}
